<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Resumen Cap 2/3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Resumen 2 - 3_files/libs/clipboard/clipboard.min.js"></script>
<script src="Resumen 2 - 3_files/libs/quarto-html/quarto.js"></script>
<script src="Resumen 2 - 3_files/libs/quarto-html/popper.min.js"></script>
<script src="Resumen 2 - 3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Resumen 2 - 3_files/libs/quarto-html/anchor.min.js"></script>
<link href="Resumen 2 - 3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Resumen 2 - 3_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Resumen 2 - 3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Resumen 2 - 3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Resumen 2 - 3_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Resumen Cap 2/3</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p><strong>Integrantes:</strong> María José Bustamante - Nicolás Jadán</p>
<p><strong>Carrera:</strong> Biomedicina</p>
<section id="capítulo-2" class="level1">
<h1>CAPÍTULO 2</h1>
</section>
<section id="aprendizaje-estadístico" class="level1">
<h1>Aprendizaje estadístico</h1>
<section id="qué-es-el-aprendizaje-estadístico" class="level2">
<h2 class="anchored" data-anchor-id="qué-es-el-aprendizaje-estadístico">¿Qué es el aprendizaje estadístico?</h2>
<p>Ayuda a determinar si existe una relación entre las variables de interés para su futura aplicación.</p>
<p>Variable de entrada (input): Suelen denotarse como “X” y con un subídice para diferenciarlas. Se conocen como; predictores, características y variables independientes.</p>
<p>Variable de salida (output): Se denota como “Y”. Conocida generalmente como variable dependiente o de respuesta.</p>
<p>El aprendizaje estadístico se refiere a un conjunto de enfoques para estimar <em>f</em> que es una función fija pero desconocida que representa información sistemática que brinda X acerca de Y.</p>
<section id="cómo-estimar-f" class="level3">
<h3 class="anchored" data-anchor-id="cómo-estimar-f">¿Cómo estimar <em>f</em>?</h3>
<p><strong>Predicción</strong></p>
<p>Generalmente se suele tener los datos de entrada pero la parte difícil es obtener la salida. Esto se puede solucionar usando:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/predicci%C3%B3n.png" width="82" height="34" class="figure-img"></p>
</figure>
</div>
<p>f: estimación para f</p>
<p>y: predicción resultante</p>
<p>Un ejemplo se muestra en la siguiente imagen:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/imagen%20prediccion.png" class="img-fluid figure-img" width="283"></p>
</figure>
</div>
<p>El gráfico muestra los ingresos en función de los años de educación y antigüedad en el conjunto de datos Renta. La superficie azul representa la verdadera relación subyacente entre los ingresos y los años de educación y antigüedad, que se conoce porque los datos son simulados. Los puntos rojos indican los valores de estas cantidades para 30 individuos.</p>
<p>La exactitud de y depende de dos tipos de error:</p>
<ul>
<li><p>Error reducible: Se refiere a la precisión de las predicciones que puede mejorar implementando mejores algoritmos para estimar f(X).</p></li>
<li><p>Error irreducible: Aunque fuera posible obtener la mejor estimación de f(X), seguirá existiendo un cierto nivel de incertidumbre ya que siempre existen dependencias de la variable objetivo con otras variables que no se están considerando o simplemente por procesos debidos al azar. Esto es lo que se conoce como error irreducible. Siempre proporcionará un límite superior en la precisión de la predicción para Y.</p></li>
</ul>
<p><strong>Inferencia</strong></p>
<p>Para comprender la asociación entre Y y Xp se pueden plantear las siguientes preguntas:</p>
<ol type="1">
<li><p><em>¿Qué predictores se asocian a la respuesta?</em></p></li>
<li><p><em>¿Cuál es la relación entre la respuesta y cada predictor?</em></p></li>
<li><p><em>¿Puede resumirse adecuadamente la relación entre Y y cada predictor mediante una ecuación lineal, o la relación es más complicada?</em></p></li>
</ol>
<p>Algunos modelos podrían utilizarse tanto para la predicción como para la inferencia, dependiendo delobjetivo final. Por ejemplo, los modelos lineales permiten una inferencia relativamente sencilla y predecible entre modelos lineales, pero puede que no produzcan predicciones tan precisas como otros enfoques. Por el contrario, algunos de los enfoques no lineales pueden brindar información bastante precisas para Y.</p>
</section>
</section>
<section id="cómo-estimamos-f" class="level2">
<h2 class="anchored" data-anchor-id="cómo-estimamos-f">¿Cómo estimamos f?</h2>
<p><strong>Métodos paramétricos</strong>: Abarcan un enfoque basado en modelos de dos pasos:</p>
<ol type="1">
<li><p>Suposición sobre la forma funcional para el modelo. Ej: f es lineal en X.</p></li>
<li><p>Después de seleccionar el modelo se requiere de un procedimiento que utilice los datos de entrenamiento para ajustar o entrenar el modelo.</p></li>
</ol>
<p>El método más común para ajustar un modelo es el de mínimos cuadrados.</p>
<p>Ejemplo:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/lineal%20mod.png" class="img-fluid figure-img" width="377"></p>
<p></p><figcaption class="figure-caption"><em>Modelo lineal ajustado por mínimos cuadrados a datos de ingresos. Las observaciones se muestran en rojo, y el plano amarillo indica el ajuste por mínimos cuadrados a los datos.</em></figcaption><p></p>
</figure>
</div>
<p>El modelo paramétrico reduce el problema para estimar f ya que se presenta como un conjunto de parámetros en el modelo lineal caso contario se debería ajustar f a una función arbitraria.</p>
<p>La desventaja de este modelo es que cuando el modelo elegido se aleje demasiado la estimación será deficiente y para resolver esto se debería estimar una mayor cantidad de parámetros lo que a su vez podría provocar un sobreaajuste de datos.</p>
<p><strong>Métodos no paramétricos:</strong> Buscan una estimación de f que se acerque lo más posible a los puntos de datos sin que sea demasiado aproximada. Se ajustan fácilmente a una gama más amplia de formas posibles de f.</p>
<p>Una desventaja que presentan es que se necesita un gran número de observaciones para obtener una estimación precisa de f.</p>
</section>
<section id="el-equilibrio-entre-la-precisión-de-la-predicción-y-la-interpretabilidad-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="el-equilibrio-entre-la-precisión-de-la-predicción-y-la-interpretabilidad-del-modelo">El equilibrio entre la precisión de la predicción y la interpretabilidad del modelo</h2>
<p>Existen métodos menos flexible o menos restrictivos en el sentido de que sólo pueden producir una gama relativamente pequeña de formas para estimar f.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/flexibilidad.png" class="img-fluid figure-img" width="467"></p>
<p></p><figcaption class="figure-caption"><em>Representación de la relación entre flexibilidad e interpretabilidad, utilizando diferentes métodos de aprendizaje estadístico. En general, a medida que aumenta la flexibilidad de un método, disminuye su interpretabilidad.</em></figcaption><p></p>
</figure>
</div>
<p><em>Modelo restrictivo:</em> Es útil cuando el principal interés es la inferencia, debido a que es más interpretable.</p>
<p><em>Modelos flexibles:</em> Pueden guiar a estimaciones muy complicadas de f en las que es difícil comprender cómo se asocia cualquier predictor con la respuesta.</p>
<ul>
<li><p>lasso: es un enfoque menos flexible y más interpretable que la regresión lineal proque en el modelo final la respuesta sólo estará relacionada con el modelo final.</p></li>
<li><p>Modelos aditivos generalizados (GAM): Más felxibles que la regresión lineal, pero menos interpretables ya que la relación entre cada predictor y respuesta se representa mediante una curva.</p></li>
<li><p>Modelos no lineales: bagging, boosting, máquinas de soporte de vectores y redes neuronales.</p></li>
</ul>
</section>
<section id="aprendizaje-supervisado-frente-a-aprendizaje-no-supervisado" class="level2">
<h2 class="anchored" data-anchor-id="aprendizaje-supervisado-frente-a-aprendizaje-no-supervisado">Aprendizaje supervisado frente a aprendizaje no supervisado</h2>
<p>Supervisado: Para cada observación de los predictores hay una respesta asociada. Permite predecir con exactitud la prespuesta para futuras predicciones o comprender mejor la relaxción entre predictores y respuesta.</p>
<p>No supervisado: Se carece de una variable de respuesta que pueda supervisar el análisis. Es decir no hay una respuesta asociada al predictor, por lo que no e sposible ajustar a un modelo de regresión lineal.</p>
</section>
<section id="problemas-de-regresión-frente-a-problemas-de-clasificación" class="level2">
<h2 class="anchored" data-anchor-id="problemas-de-regresión-frente-a-problemas-de-clasificación">Problemas de regresión frente a problemas de clasificación</h2>
<p>Variables cuantitativas: Toman valores numéricos. Ej: Estatura, edad o ingresos.</p>
<p>Variables cualitativas: Toman valores en clases o categorías. Ej: Estado cívil, marcas de productos o diagnósticos.</p>
<p>La regresión logística es un método de clasificación binaria. Es bastante común seleccionar los métodos de aprendizaje estadístico en función de si la respuesta es cuantitativa o cualitativa, es decir, se puede usar la regresión lineal cuando es cuantitativa y la regresión logística cuando es cualitativa.</p>
</section>
</section>
<section id="evaluación-de-la-precisión-de-los-modelos" class="level1">
<h1>Evaluación de la precisión de los modelos</h1>
<p>En en estadística: ningún método domina a todos los demás en todos los conjuntos de datos posibles.</p>
<section id="medir-la-calidad-del-ajuste" class="level2">
<h2 class="anchored" data-anchor-id="medir-la-calidad-del-ajuste">Medir la calidad del ajuste</h2>
<p>Para evaluar el rendimiento de un método de aprendizaje estadístico se requiere cuantificar hasta qué punto el valor de respuesta predicho para una observación dada se aproxima al valor de respuesta verdadero para esa observación.</p>
<p><em>Error cuadrático medio (MSE):</em> será pequeño si las respuestas predichas están muy cerca de las respuestas verdaderas, y será grande si para algunas de las observaciones, las respuestas predichas y verdaderas difieren sustancialmente.</p>
<p>Se calcula utilizando los datos de entrenamiento que se usaron para jaustar el modelo</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/MSE.png" class="img-fluid figure-img" width="481"></p>
<p></p><figcaption class="figure-caption"><em><strong>Izquierda:</strong> Datos simulados a partir de f, mostrados en negro. Se muestran tres estimaciones de f: la línea de regresión lineal (curva naranja) y dos splines de suavizado (curvas azul y verde). (curvas azul y verde). <strong>Derecha:</strong> MSE de entrenamiento (curva gris), MSE de prueba (curva roja roja) y el MSE de prueba mínimo posible de todos los métodos (línea discontinua). Los cuadrados MSE de entrenamiento y prueba de los tres ajustes mostrados en el panel izquierdo.</em></figcaption><p></p>
</figure>
</div>
<p>En la imagen en la parte izquierda se puede ver que a medida que aumenta el nivel de flexibilidad, las curvas se ajustan mejor a los datos observados. La curva verde es la más flexible y se ajusta muy bien a los datos; sin embargo, observamos que se ajusta mal a la f verdadera (mostrada en negro) porque es demasiado ondulada.</p>
<p>En la parte derecha La curva gris muestra el MSE medio de entrenamiento en función de la flexibilidad, o más formalmente de los grados de libertad (flexibilidad de la curva). Los cuadrados naranja, azul y verde indican los MSE asociados a las curvas.</p>
<p>En este ejemplo, la verdadera f no es lineal, por lo que el ajuste lineal naranja no es lo suficientemente flexible para estimar bien f.&nbsp;La curva verde tiene el MSE de entrenamiento más bajo de los tres métodos, ya que corresponde al más flexible de ellos. El spline de suavizado representado por la curva azul se aproxima al óptimo.</p>
<p>En la parte derecha de la figura, a medida que aumenta la flexibilidad del método de aprendizaje estadístico, observamos un descenso monótono en el tiempo de entrenamiento. Es decir, a medida que aumenta la flexibilidad del modelo aumenta, el MSE de entrenamiento disminuirá.</p>
<p>Cuando un método determinado produce un MSE de entrenamiento pequeño pero un MSE de prueba grande, se dice que se están sobreajustando los datos.</p>
</section>
<section id="la-relación-entre-sesgo-y-varianza" class="level2">
<h2 class="anchored" data-anchor-id="la-relación-entre-sesgo-y-varianza">La relación entre sesgo y varianza</h2>
<p>Para minimizar el error de prueba esperado se requiere seleccionar un método de aprendizaje estadístico que consiga simultáneamente baja varianza y bajo sesgo.</p>
<p>Varianza: Se refire a la cantidad en la que <em>f</em> cambiaría si la estimación se realizara usando un conjunto de datos de enttrenamiento diferente. Lo ideal es que la estimación de f no varíe demasiado. En general los métodos estadísticos más flexibles tienen mayor varianza.</p>
<p>Sesgo: Es el error que se introduce al aproximar un problema de la vida real a un modelo muy simple o sencillo. Es poco probable que un problema de la vida real tenga una relación lineal tan sencilla, por lo que realizar una regresión lineal dará lugar a cierto sesgo en la estimación de f.</p>
<p>La varianza es intrínsecamente una cantidad no negativa, y el sesgo al cuadrado también es no negativo.</p>
<p>A medida que utilicemos métodos más flexibles, la varianza aumentará y el sesgo disminuirá.</p>
<p>Un buen rendimiento del conjunto de prueba de un método de aprendizaje estadístico requiere una varianza baja, así como un equilibrio entre sesgo y varianza.</p>
</section>
<section id="el-entorno-de-clasificación" class="level2">
<h2 class="anchored" data-anchor-id="el-entorno-de-clasificación">El entorno de clasificación</h2>
<p>Las tasas de error resultantes son de especial interés para la aplicación del clasificador a observaciones de prueba que no fueron utilizadas en el entrenamiento. Un buen clasificador es aquel en el que el error de prueba es mínimo.</p>
<section id="el-clasificador-de-bayes" class="level3">
<h3 class="anchored" data-anchor-id="el-clasificador-de-bayes">El clasificador de Bayes</h3>
<p>Asigna cada observación a la clase más probable dados sus valores predictores. En un problema de dos clases en el que sólo hay dos posibles valores de respuesta, el clasificador de Bayes corresponde a la predicción de la clase uno si Pr(Y = 1|X = x0) &gt; 0,5, y la clase dos en caso contrario.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/bayes.png" class="img-fluid figure-img" width="411"></p>
<p></p><figcaption class="figure-caption"><em>Un conjunto de datos simulados compuesto por 100 observaciones en cada uno de dos grupos, indicados en azul y en naranja. La línea discontinua morada representa el límite de decisión de Bayes. La cuadrícula de fondo naranja indica la región en la que una observación de prueba se asignará a la clase naranja, y la cuadrícula de fondo azul azul indica la región en la que una observación de prueba se asignará a la clase azul. a la clase azul.</em></figcaption><p></p>
</figure>
</div>
<p>En la imagen los círculos naranja y azules corresponden a observaciones de entrenamiento que pertenecen a dos clases diferentes.</p>
<p>Para cada valor de X1 y X2, existe una probabilidad diferente de que la respuesta sea naranja o azul.</p>
<p>La región sombreada en naranja refleja el conjunto de puntos para los que Pr(Y = naranja|X) es superior al 50 %, mientras que la región sombreada en azul indica el conjunto de puntos cuya probabilidad es inferior al 50 %.</p>
<p>La línea discontinua morada representa los puntos en los que la probabilidad es exactamente del 50 %. Esto se denomina el <strong>límite de decisión de Bayes.</strong></p>
</section>
<section id="k-nearest-neighbors" class="level3">
<h3 class="anchored" data-anchor-id="k-nearest-neighbors">K-Nearest Neighbors</h3>
<p>Es utilizado para trabajar con datos reales. Es un algoritmo no supervisado donde “K” representa el número de “grupos” (clusters) a clasificar y el K-neighbor más cercano “K” representa el número de “vecinos” considerados en los “n” grupos del clasificador. En otras palabras busca en las observaciones más cercanas a la que se está tratando de predecir y clasifica el punto de interés basado en la mayoría de datos que le rodean.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/k-neig.png" class="img-fluid figure-img" width="446"></p>
<p></p><figcaption class="figure-caption"><em>Comparación de los límites de decisión KNN (curvas negras obtenidas utilizando K = 1 y K = 100 en los datos de la Figura 2.13. Con K = 1, el límite de decisión es demasiado flexible, mientras que con K = 100 no es suficientemente flexible. El límite de decisión de Bayes se muestra como una línea discontinua morada.</em></figcaption><p></p>
</figure>
</div>
<p>La imagen muestra dos ajustes KNN a los datos simulados, utilizando K = 1 y K = 100. Cuando K = 1, el límite de decisión es excesivamente flexible y encuentra patrones en los datos que no se corresponden con el límite de decisión de Bayes. Esto corresponde a un clasificador que tiene un sesgo bajo pero una varianza muy alta. A medida que K aumenta, el método se vuelve menos flexible y produce una frontera de decisión cercana a la lineal. Esto corresponde a un clasificador de baja varianza pero alto sesgo. En este conjunto de datos simulados, ni K = 1 ni K = 100 dan buenas predicciones: tienen tasas de error de prueba de 0,1695 y 0,1925, respectivamente.</p>
</section>
</section>
</section>
<section id="capítulo-3" class="level1">
<h1>CAPÍTULO 3</h1>
</section>
<section id="regresión-linear" class="level1">
<h1>Regresión linear</h1>
<p>La regresión lineal, es un enfoque simple pero poderoso para el aprendizaje supervisado. El capítulo cubre las ideas clave que subyacen al modelo de regresión lineal, así como el enfoque de mínimos cuadrados que se usa más comúnmente para ajustar este modelo. También analiza algunas preguntas importantes que podríamos tratar de abordar al analizar datos y hacer recomendaciones para planes de marketing basados en análisis estadísticos. En general, el capítulo sirve como base para métodos de aprendizaje estadístico más avanzados y proporciona una descripción general de cómo se puede usar la regresión lineal para predecir respuestas cuantitativas.</p>
<section id="regresión-linear-simple" class="level2">
<h2 class="anchored" data-anchor-id="regresión-linear-simple">Regresión linear simple</h2>
<p>La regresión lineal simple es un método estadístico utilizado para predecir una variable de respuesta cuantitativa basada en una única variable predictora. Asume que existe una relación aproximadamente lineal entre el predictor y las variables de respuesta. La relación lineal se puede expresar matemáticamente como Y ≈ β0 + β1X, donde Y es la variable de respuesta, X es la variable predictora, β0 y β1 son coeficientes que representan la intersección y la pendiente de la línea, respectivamente. El método se usa comúnmente en varios campos, como marketing, finanzas y ciencias sociales, para analizar datos y hacer predicciones.</p>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p>Estimating the Coefficients</p>
<p>Estimar los coeficientes es un paso crucial en la regresión lineal simple. En la práctica, los coeficientes β0 y β1 son desconocidos, por lo que antes de que podamos usar el modelo de regresión lineal para hacer predicciones, debemos usar datos para estimar estos coeficientes. Se proporciona una discusión detallada sobre cómo estimar estos coeficientes usando el enfoque de mínimos cuadrados. El enfoque de mínimos cuadrados implica encontrar los valores de β0 y β1 que minimizan la suma de los residuos cuadrados entre los valores predichos y reales de la variable de respuesta.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/reg.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 1. Para los datos de publicidad, los mínimos cuadrados se ajustan a la regresión de las ventas en TV se muestra. El ajuste se obtiene minimizando la suma residual de cuadrícula. Cada segmento de línea gris representa un residuo. En este caso un ajuste lineal capta la esencia de la relación, aunque sobrestima la tendencia en la izquierda de la parcela.</figcaption><p></p>
</figure>
</div>
</section>
<section id="evaluación-de-la-precisión-de-las-estimaciones-del-coeficiente" class="level3">
<h3 class="anchored" data-anchor-id="evaluación-de-la-precisión-de-las-estimaciones-del-coeficiente">Evaluación de la precisión de las estimaciones del coeficiente</h3>
<p>Es un paso importante en la regresión lineal simple. Una vez que hemos estimado los coeficientes β0 y β1, es natural querer cuantificar hasta qué punto estas estimaciones son precisas. presenta una discusión detallada sobre cómo calcular los errores estándar, las estadísticas t y los valores p para estas estimaciones de coeficientes. Estas estadísticas se pueden utilizar para comprobar si existe una relación lineal significativa entre las variables predictoras y de respuesta, así como para construir intervalos de confianza para los coeficientes. Se analiza cómo interpretar estas estadísticas y cómo se pueden usar para hacer inferencias sobre los parámetros de la población. En general, evaluar la precisión de las estimaciones de los coeficientes es un paso esencial en la regresión lineal simple, ya que nos permite determinar si nuestro modelo es estadísticamente significativo y si nuestras estimaciones son confiables.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fig4.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Fig 3. Un conjunto de datos simulado. Izquierda: La línea roja representa la verdadera relación, f(X)=2+3X, que se conoce como la línea de regresión de población. El la línea azul es la línea de mínimos cuadrados; es la estimación de mínimos cuadrados para f(X) basada en los datos observados, mostrados en negro. Derecha: La línea de regresión de la población es nuevamente se muestra en rojo, y la línea de mínimos cuadrados en azul oscuro. En azul claro, diez menos Se muestran líneas cuadradas, cada una calculada sobre la base de un conjunto aleatorio separado de observaciones. Cada línea de mínimos cuadrados es diferente, pero en promedio, los mínimos cuadrados Las líneas están bastante cerca de la línea de regresión de la población.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tabl1.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">TABLA 1. Para los datos de Publicidad, coeficientes del modelo de mínimos cuadrados para la regresión del número de unidades vendidas sobre el presupuesto de publicidad televisiva. Un aumento de $1,000 en el presupuesto de publicidad televisiva se asocia con un aumento en las ventas de alrededor de 50 unidades. (Recuerde que la variable de ventas está en miles de unidades, y la La variable TV está en miles de dólares).</figcaption><p></p>
</figure>
</div>
</section>
<section id="evaluar-la-precisión-del-modelo" class="level3">
<h3 class="anchored" data-anchor-id="evaluar-la-precisión-del-modelo">Evaluar la precisión del modelo</h3>
<p>Es un paso importante en la regresión lineal simple. Una vez que hemos rechazado la hipótesis nula a favor de la hipótesis alternativa, es natural querer cuantificar hasta qué punto el modelo se ajusta a los datos. La calidad de un ajuste de regresión lineal generalmente se evalúa utilizando dos cantidades relacionadas: el error estándar residual (RSE) y la estadística R-cuadrado (R2). El RSE mide la cantidad promedio que la variable de respuesta se desvía del valor predicho, mientras que R2 mide qué parte de la variabilidad en la variable de respuesta puede explicarse por la variable predictora.</p>
<section id="error-estándar-residual" class="level4">
<h4 class="anchored" data-anchor-id="error-estándar-residual">Error estándar residual</h4>
<p>El error estándar residual (RSE) es una medida de la cantidad promedio que la variable de respuesta se desvía del valor predicho en la regresión lineal simple. Se especifica como calcular RSE usando la fórmula RSE = sqrt(RSS/(n-2)), donde RSS es la suma residual de los cuadrados y n es el tamaño de la muestra. El RSE mide la variabilidad de la variable de respuesta que no está explicada por la variable predictora, y se puede utilizar para evaluar qué tan bien se ajusta nuestro modelo a los datos. Un RSE más pequeño indica un mejor ajuste, mientras que un RSE más grande indica un peor ajuste. Analiza cómo interpretar RSE y cómo se puede usar junto con otras estadísticas como R-squared para evaluar la precisión del modelo. Nos permite evaluar qué tan bien se ajusta nuestro modelo a nuestros datos.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tab2.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">TABLA 2. Para los datos de Publicidad, más información sobre los mínimos cuadrados modelo para la regresión del número de unidades vendidas sobre el presupuesto de publicidad televisiva.</figcaption><p></p>
</figure>
</div>
</section>
</section>
</section>
<section id="regresión-lineal-múltiple" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal-múltiple">Regresión lineal múltiple</h2>
<p>La regresión lineal múltiple es una extensión de la regresión lineal simple que nos permite modelar la relación entre una variable de respuesta y varias variables predictoras. Se muestra cómo realizar una regresión lineal múltiple utilizando el enfoque de mínimos cuadrados. El enfoque de mínimos cuadrados implica encontrar los valores de β0, β1, β2, ..., βp que minimizan la suma de los residuos cuadrados entre los valores predichos y reales de la variable de respuesta. Muestra como interpretar estos coeficientes estimados y cómo probar si son estadísticamente significativos mediante la prueba de hipótesis. Además, el capítulo cubre temas como la selección de modelos, la multicolinealidad y los efectos de interacción en la regresión lineal múltiple. En general, la regresión lineal múltiple es una herramienta poderosa para modelar relaciones complejas entre variables y se puede utilizar en una amplia gama de aplicaciones en diversos campos, como la economía, las finanzas y las ciencias sociales.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/tbl%203.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Tabla 3. Modelos de regresión lineal más simples para los datos publicitarios. Coeficientes del modelo de regresión lineal simple para el número de unidades vendidas en Top: presupuesto de publicidad en radio y Abajo: presupuesto de publicidad en periódicos. Un aumento de $1,000 en el gasto en publicidad por radio está asociado con un aumento promedio en ventas en alrededor de 203 unidades, mientras que el mismo aumento en el gasto en publicidad en periódicos está asociado con un aumento promedio en las ventas de alrededor de 55 unidades. (Nota que la variable de ventas está en miles de unidades, y la radio y el periódico las variables están en miles de dólares).</figcaption><p></p>
</figure>
</div>
<section id="estimación-de-los-coeficientes-de-regresión" class="level3">
<h3 class="anchored" data-anchor-id="estimación-de-los-coeficientes-de-regresión">Estimación de los coeficientes de regresión</h3>
<p>Se analiza cómo estimar los coeficientes de regresión en Regresión lineal simple utilizando el enfoque de mínimos cuadrados. El enfoque de mínimos cuadrados implica encontrar los valores de β0 y β1 que minimizan la suma de los residuos cuadrados entre los valores predichos y reales de la variable de respuesta. El capítulo proporciona una discusión detallada sobre cómo calcular estas estimaciones de coeficientes usando fórmulas y cómo interpretarlas en el contexto de nuestros datos. Además, el capítulo cubre temas como errores estándar, estadísticas t y valores p para estas estimaciones de coeficientes. Estas estadísticas se pueden utilizar para evaluar la precisión del modelo y construir intervalos de confianza para los coeficientes. En general, estimar los coeficientes de regresión es un paso esencial en la regresión lineal simple, ya que nos permite hacer predicciones basadas en nuestros datos y evaluar qué tan bien se ajusta nuestro modelo a nuestros datos.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sd.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 4. En un entorno tridimensional, con dos predictores y una respuesta, la línea de regresión de mínimos cuadrados se convierte en un plano. El avión es elegido para minimizar la suma de las distancias verticales al cuadrado entre cada observación (mostrado en rojo) y el avión.</figcaption><p></p>
</figure>
</div>
</section>
<section id="tabla-4.-para-los-datos-de-publicidad-las-estimaciones-del-coeficiente-de-mínimos-cuadrados-de-la-regresión-lineal-múltiple-del-número-de-unidades-vendidas-en-televisión-radio-y-periódicos-presupuestos-publicitarios" class="level3">
<h3 class="anchored" data-anchor-id="tabla-4.-para-los-datos-de-publicidad-las-estimaciones-del-coeficiente-de-mínimos-cuadrados-de-la-regresión-lineal-múltiple-del-número-de-unidades-vendidas-en-televisión-radio-y-periódicos-presupuestos-publicitarios"><img src="images/te4.jpg" class="img-fluid" alt="TABLA 4. Para los datos de publicidad, las estimaciones del coeficiente de mínimos cuadrados de la regresión lineal múltiple del número de unidades vendidas en televisión, radio y periódicos presupuestos publicitarios"></h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sss.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Table 5.Matriz de correlación de TV, radio, periódico y ventas para el Datos publicitarios.</figcaption><p></p>
</figure>
</div>
</section>
<section id="algunas-preguntas-importantes" class="level3">
<h3 class="anchored" data-anchor-id="algunas-preguntas-importantes">Algunas preguntas importantes</h3>
<p>Cuando realizamos una regresión lineal múltiple, por lo general estamos interesados ​​en respondiendo algunas preguntas importantes. 1. ¿Al menos uno de los predictores X1, X2,...,Xp es útil para predecir ¿la respuesta? 2. ¿Todos los predictores ayudan a explicar Y , o es solo un subconjunto del predictores útil? 3. ¿Qué tan bien se ajusta el modelo a los datos? 4. Dado un conjunto de valores predictores, ¿qué valor de respuesta deberíamos predecir? y ¿qué tan precisa es nuestra predicción? Ahora abordaremos cada una de estas preguntas por separado.</p>
<p><br>
Uno: ¿Existe una relación entre la respuesta y los predictores?</p>
<p>Dos: decidir sobre variables importantes<br>
Tres: ajuste del modelo Cuatro: predicciones</p>
</section>
</section>
<section id="otras-consideraciones-en-el-modelo-de-regresión" class="level2">
<h2 class="anchored" data-anchor-id="otras-consideraciones-en-el-modelo-de-regresión">Otras consideraciones en el modelo de regresión</h2>
<section id="predictores-cualitativos" class="level3">
<h3 class="anchored" data-anchor-id="predictores-cualitativos">Predictores cualitativos</h3>
<p>En el contexto de la regresión lineal, los predictores cualitativos son variables que toman valores no numéricos, como categorías o etiquetas. Por ejemplo, en el conjunto de datos de Crédito que se muestra en la Figura 6, la variable predictora “educación” representa los años de educación y es una variable cuantitativa, mientras que la variable predictora “calificación” representa la calificación crediticia y es una variable cualitativa. Cuando se trata de predictores cualitativos en regresión lineal, necesitamos convertirlos en variables numéricas mediante un proceso llamado codificación. Un método común para codificar predictores cualitativos se llama codificación ficticia, donde creamos variables binarias para representar cada categoría del predictor cualitativo.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/sda.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 6. El conjunto de datos de crédito contiene información sobre saldo, antigüedad, tarjetas, educación, ingresos, límite y calificación para una cantidad de clientes potenciales</figcaption><p></p>
</figure>
</div>
</section>
<section id="extensiones-del-modelo-lineal" class="level3">
<h3 class="anchored" data-anchor-id="extensiones-del-modelo-lineal">Extensiones del modelo lineal</h3>
<p>El modelo de regresión lineal estándar hace varias suposiciones altamente restrictivas que a menudo se violan en la práctica. Dos de los supuestos más importantes establecen que la relación entre los predictores y la respuesta es aditiva y lineal. El supuesto de aditividad significa que la asociación entre un predictor Xj y la respuesta Y no depende de los valores de los otros predictores. La suposición de linealidad establece que el cambio en la respuesta Y asociado con un cambio de una unidad en Xj es constante, independientemente del valor de Xj.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/dsads.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 7. Para los datos de crédito, se muestran las líneas de mínimos cuadrados para la predicción del saldo de ingresos para estudiantes y no estudiantes. Izquierda: El modelo (3.34) estaba en forma. No hay interacción entre ingreso y estudiante. Derecha: El el modelo (3.35) se ajustaba. Existe un término de interacción entre ingreso y estudiante.</figcaption><p></p>
</figure>
</div>
<p>Para abordar estas limitaciones, existen varias extensiones del modelo lineal, como la regresión polinomial, los efectos de interacción y los modelos lineales generalizados. La regresión polinomial nos permite modelar relaciones no lineales entre los predictores y la respuesta al incluir términos de predictores de orden superior en nuestro modelo. Los efectos de interacción nos permiten modelar cómo dos o más predictores interactúan entre sí para afectar la variable de respuesta. Los modelos lineales generalizados amplían la regresión lineal para manejar variables de respuesta no normales mediante el uso de una función de enlace para relacionar la media de la variable de respuesta con una combinación lineal de predictores.</p>
<p>Estas extensiones brindan más flexibilidad en el modelado de problemas del mundo real donde las relaciones entre predictores y respuestas pueden no ser estrictamente aditivas o lineales.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/dsad.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 8. El conjunto de datos automático. Para una cantidad de autos, mpg y caballos de fuerza son mostrado. El ajuste de regresión lineal se muestra en naranja. El ajuste de regresión lineal para un el modelo que incluye caballos de fuerza2 se muestra como una curva azul. La regresión lineal apto para un modelo que incluye todos los polinomios de caballos de fuerza hasta el quinto grado es se muestra en verde</figcaption><p></p>
</figure>
</div>
</section>
<section id="relaciones-no-lineales" class="level3">
<h3 class="anchored" data-anchor-id="relaciones-no-lineales">Relaciones no lineales</h3>
<p>La regresión lineal asume una relación lineal entre la respuesta y los predictores. Sin embargo, en algunos casos, la verdadera relación entre la respuesta y los predictores puede no ser lineal. Para dar cabida a las relaciones no lineales, podemos utilizar la regresión polinomial, que es una forma sencilla de extender directamente el modelo lineal. La regresión polinomial nos permite modelar relaciones no lineales entre los predictores y la respuesta al incluir términos de predictores de orden superior en nuestro modelo</p>
</section>
<section id="problemas-potenciales" class="level3">
<h3 class="anchored" data-anchor-id="problemas-potenciales">Problemas potenciales</h3>
<section id="no-linealidad-de-las-relaciones-respuesta-predictor" class="level4">
<h4 class="anchored" data-anchor-id="no-linealidad-de-las-relaciones-respuesta-predictor">1. No linealidad de las relaciones respuesta-predictor</h4>
<p>La no linealidad significa que la relación entre la variable de respuesta y una o más variables predictoras no es lineal, lo que puede conducir a estimaciones sesgadas o ineficientes de los coeficientes de regresión. Para abordar la no linealidad, podemos usar la regresión polinomial, que nos permite modelar relaciones no lineales entre los predictores y la respuesta al incluir términos de predictores de orden superior en nuestro modelo.</p>
<p><img src="images/jj.jpg" class="img-fluid"></p>
</section>
<section id="section-1" class="level4">
<h4 class="anchored" data-anchor-id="section-1"></h4>
<ol start="2" type="1">
<li>Correlación de términos de error.</li>
</ol>
<p>Una suposición importante del modelo de regresión lineal es que los términos de error, ε1, ε2, ..., εn, no están correlacionados. Esto significa que si los errores no están correlacionados, el hecho de que εi sea positivo proporciona poca o ninguna información sobre el signo de εi+1. Los errores estándar que se calculan para los coeficientes de regresión estimados o los valores ajustados se basan en la suposición de términos de error no correlacionados. Si de hecho existe una correlación entre los términos de error, entonces los errores estándar estimados tenderán a subestimar los errores estándar verdaderos.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/fr.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 10. Gráficas de residuos de conjuntos de datos de series de tiempo simulados generados con diferentes niveles de correlación ρ entre términos de error para puntos de tiempo adyacentes.</figcaption><p></p>
</figure>
</div>
</section>
<section id="figura-11.-parcelas-residuales.-en-cada-parcela-la-línea-roja-es-un-ajuste-suave-a-la-residuales-destinados-a-facilitar-la-identificación-de-una-tendencia.-las-líneas-azules-rastrean-el-cuantiles-externos-de-los-residuales-y-enfatizar-patrones.-izquierda-la-forma-de-embudo-indica-heterocedasticidad.-derecha-la-respuesta-se-ha-transformado-logarítmicamente-y-ahora-no-hay-evidencia-de-heteroscedasticidad." class="level4">
<h4 class="anchored" data-anchor-id="figura-11.-parcelas-residuales.-en-cada-parcela-la-línea-roja-es-un-ajuste-suave-a-la-residuales-destinados-a-facilitar-la-identificación-de-una-tendencia.-las-líneas-azules-rastrean-el-cuantiles-externos-de-los-residuales-y-enfatizar-patrones.-izquierda-la-forma-de-embudo-indica-heterocedasticidad.-derecha-la-respuesta-se-ha-transformado-logarítmicamente-y-ahora-no-hay-evidencia-de-heteroscedasticidad."><img src="images/gres.jpg" class="img-fluid" alt="FIGURA 11. Parcelas residuales. En cada parcela, la línea roja es un ajuste suave a la residuales, destinados a facilitar la identificación de una tendencia. Las líneas azules rastrean el cuantiles externos de los residuales y enfatizar patrones. Izquierda: La forma de embudo indica heterocedasticidad. Derecha: la respuesta se ha transformado logarítmicamente y ahora no hay evidencia de heteroscedasticidad."></h4>
<ol start="3" type="1">
<li>Varianza no constante de los términos de error.</li>
</ol>
<p>Otra suposición importante del modelo de regresión lineal es que los términos de error tienen una varianza constante, Var(εi)=σ2. Los errores estándar, los intervalos de confianza y las pruebas de hipótesis asociadas con el modelo lineal se basan en esta suposición. Si la varianza de los términos de error no es constante, los errores estándar estimados estarán sesgados y las pruebas de hipótesis y los intervalos de confianza no serán válidos. Una forma de abordar la varianza no constante es usar la regresión de mínimos cuadrados ponderados, que asigna pesos más grandes a las observaciones con varianzas más pequeñas y pesos más pequeños a las observaciones con varianzas más grandes.</p>
</section>
<section id="figura-12.-izquierda-la-línea-de-regresión-de-mínimos-cuadrados-se-muestra-en-rojo-y-la-la-línea-de-regresión-después-de-eliminar-el-valor-atípico-se-muestra-en-azul.-centro-el-residual-la-trama-identifica-claramente-el-valor-atípico.-derecha-el-valor-atípico-tiene-un-residuo-estudentizado-de-6-típicamente-esperamos-valores-entre-3-y-3." class="level4">
<h4 class="anchored" data-anchor-id="figura-12.-izquierda-la-línea-de-regresión-de-mínimos-cuadrados-se-muestra-en-rojo-y-la-la-línea-de-regresión-después-de-eliminar-el-valor-atípico-se-muestra-en-azul.-centro-el-residual-la-trama-identifica-claramente-el-valor-atípico.-derecha-el-valor-atípico-tiene-un-residuo-estudentizado-de-6-típicamente-esperamos-valores-entre-3-y-3."><img src="images/sdas.jpg" class="img-fluid" alt="FIGURA 12. Izquierda: La línea de regresión de mínimos cuadrados se muestra en rojo, y la la línea de regresión después de eliminar el valor atípico se muestra en azul. Centro: El residual la trama identifica claramente el valor atípico. Derecha: El valor atípico tiene un residuo estudentizado de 6; típicamente esperamos valores entre −3 y 3."></h4>
<ol start="4" type="1">
<li>Valores atípicos.</li>
</ol>
<p>Un valor atípico es un punto para el cual yi está lejos del valor predicho por el modelo. Los valores atípicos pueden surgir por una variedad de razones, como el registro incorrecto de una observación durante la recopilación de datos. Los valores atípicos pueden tener un gran efecto en los coeficientes de regresión estimados y pueden conducir a estimaciones sesgadas o ineficientes. Una forma de abordar los valores atípicos es utilizar métodos de regresión robustos, que son menos sensibles a los valores atípicos que la regresión ordinaria de mínimos cuadrados. Otro enfoque es identificar y eliminar los valores atípicos del conjunto de datos, aunque esto debe hacerse con precaución y solo después de una cuidadosa consideración de las razones de los valores atípicos.</p>
</section>
<section id="figura-13.-izquierda-la-observación-41-es-un-punto-de-alto-apalancamiento-mientras-que-la-20-no-lo-es.-la-línea-roja-es-el-ajuste-a-todos-los-datos-y-la-línea-azul-es-el-ajuste-con-la-observación.-41-eliminados.-centro-la-observación-roja-no-es-inusual-en-términos-de-su-valor-x1-o-su-valor-x2-pero-aún-queda-fuera-de-la-mayor-parte-de-los-datos-y-por-lo-tanto-tiene-un-alto-aprovechar.-derecha-la-observación-41-tiene-un-alto-apalancamiento-y-un-alto-residual." class="level4">
<h4 class="anchored" data-anchor-id="figura-13.-izquierda-la-observación-41-es-un-punto-de-alto-apalancamiento-mientras-que-la-20-no-lo-es.-la-línea-roja-es-el-ajuste-a-todos-los-datos-y-la-línea-azul-es-el-ajuste-con-la-observación.-41-eliminados.-centro-la-observación-roja-no-es-inusual-en-términos-de-su-valor-x1-o-su-valor-x2-pero-aún-queda-fuera-de-la-mayor-parte-de-los-datos-y-por-lo-tanto-tiene-un-alto-aprovechar.-derecha-la-observación-41-tiene-un-alto-apalancamiento-y-un-alto-residual."><img src="images/outl.jpg" class="img-fluid" alt="FIGURA 13. Izquierda: la observación 41 es un punto de alto apalancamiento, mientras que la 20 no lo es. La línea roja es el ajuste a todos los datos, y la línea azul es el ajuste con la observación. 41 eliminados. Centro: la observación roja no es inusual en términos de su valor X1 o su valor X2, pero aún queda fuera de la mayor parte de los datos y, por lo tanto, tiene un alto aprovechar. Derecha: la observación 41 tiene un alto apalancamiento y un alto residual."></h4>
<ol start="5" type="1">
<li>Puntos de alto apalancamiento.</li>
</ol>
<p>Los puntos de alto apalancamiento son observaciones con un valor inusual para xi. Estos puntos pueden tener un gran efecto en los coeficientes de regresión estimados y pueden conducir a estimaciones sesgadas o ineficientes. Una forma de identificar puntos de alto apalancamiento es calcular la estadística de apalancamiento, que mide la influencia de cada observación en los coeficientes de regresión estimados. Un punto de alto apalancamiento es aquel para el cual la estadística de apalancamiento es mucho mayor que el valor promedio de la estadística de apalancamiento para todas las observaciones. Para abordar los puntos de alto apalancamiento, podemos usar herramientas de diagnóstico como gráficos residuales y la distancia de Cook para identificar observaciones influyentes y potencialmente eliminarlas del conjunto de datos.</p>
</section>
<section id="colinealidad." class="level4">
<h4 class="anchored" data-anchor-id="colinealidad.">6. Colinealidad.</h4>
<p>La colinealidad se refiere a la situación en la que dos o más variables predictoras están estrechamente relacionadas entre sí. La colinealidad puede dificultar la estimación de los efectos individuales de cada variable predictora sobre la variable de respuesta y puede conducir a estimaciones inestables e ineficientes de los coeficientes de regresión. Una forma de detectar la colinealidad es calcular la matriz de correlación entre las variables predictoras. Un alto coeficiente de correlación entre dos variables predictoras indica que pueden ser colineales. Para abordar la colinealidad, podemos utilizar técnicas como la regresión de componentes principales o la regresión de crestas, que pueden ayudar a estabilizar las estimaciones de los coeficientes de regresión en presencia de predictores colineales.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/jh.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 14. Diagramas de dispersión de las observaciones del conjunto de datos Credit. Izquierda: Una gráfica de edad versus límite. Estas dos variables no son colineales. Derecha: una trama de calificación versus límite. Hay alta colinealidad.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/jh1.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 15. Gráficos de contorno para los valores RSS en función de los parámetros β para varias regresiones que involucran el conjunto de datos Credit. En cada parcela, el negro los puntos representan los valores de los coeficientes correspondientes a la RSS mínima. Izquierda: Un gráfico de contorno de RSS para la regresión del equilibrio sobre la edad y el límite. El el valor mínimo está bien definido. Derecha: un gráfico de contorno de RSS para la regresión de equilibrio en calificación y límite. Debido a la colinealidad, hay muchos pares (βLimit, βRating) con un valor similar para RSS.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/te.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">TABLA 11. Los resultados de dos modelos de regresión múltiple que implican la Se muestra el conjunto de datos de crédito. El modelo 1 es una regresión de equilibrio sobre edad y límite, y el Modelo 2 una regresión de equilibrio sobre calificación y límite. El error estándar de βˆlímite aumenta 12 veces en la segunda regresión, debido a la colinealidad.</figcaption><p></p>
</figure>
</div>
</section>
</section>
</section>
<section id="el-plan-de-mercadeo" class="level2">
<h2 class="anchored" data-anchor-id="el-plan-de-mercadeo">El Plan de Mercadeo</h2>
<p>Para responder a las siete preguntas sobre los datos publicitarios que nos propusimos responder al comienzo de este capítulo, necesitamos desarrollar un plan de marketing basado en el análisis de los datos. Un enfoque para desarrollar un plan de marketing es utilizar el análisis de regresión para modelar la relación entre el presupuesto de publicidad y las ventas de productos. Podemos usar técnicas como la regresión lineal múltiple o la regresión polinomial para capturar cualquier relación no lineal entre estas variables. También podemos utilizar herramientas de diagnóstico, como gráficos de residuos y pruebas de hipótesis, para evaluar la bondad de ajuste del modelo e identificar posibles problemas, como colinealidad o valores atípicos. Con base en los resultados de nuestro análisis, podemos desarrollar un plan de marketing que se adapte a las necesidades específicas de la empresa y su público objetivo.</p>
<ol type="1">
<li>¿Existe una relación entre las ventas y el presupuesto de publicidad?</li>
<li>¿Qué tan fuerte es la relación?</li>
<li>¿Qué medios están asociados con las ventas?</li>
<li>¿Qué tan grande es la asociación entre cada medio y las ventas?</li>
<li>¿Con qué precisión podemos predecir las ventas futuras?</li>
<li>¿La relación es lineal?</li>
<li>¿Existe sinergia entre los medios publicitarios?</li>
</ol>
</section>
<section id="comparación-de-regresión-lineal-con-k-vecinos-más-cercanos" class="level2">
<h2 class="anchored" data-anchor-id="comparación-de-regresión-lineal-con-k-vecinos-más-cercanos">Comparación de regresión lineal con K-vecinos más cercanos</h2>
<p>La sección presenta una comparación del rendimiento de la regresión lineal y KNN en conjuntos de datos con relaciones levemente no lineales y fuertemente no lineales entre las variables predictoras y las variables de respuesta. Los resultados muestran que KNN puede superar la regresión lineal en los casos en que la relación entre las variables predictoras y las variables de respuesta no es lineal. Sin embargo, la elección del valor de K puede tener un impacto significativo en el rendimiento de KNN y seleccionar un valor apropiado para K puede ser un desafío. En general, la elección entre regresión lineal y KNN depende de las características específicas del conjunto de datos y los objetivos del análisis.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/holas.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 16. Gráficas de ˆf(X) usando la regresión KNN en datos bidimensionales conjunto con 64 observaciones (puntos naranjas). Izquierda: K = 1 da como resultado un ajuste de función de paso aproximado. Derecha: K = 9 produce un ajuste mucho más suave</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/ll.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 17. Gráficas de ˆf(X) usando regresión KNN en datos unidimensionales conjunto con 50 observaciones. La verdadera relación viene dada por la línea continua negra. Izquierda: La curva azul corresponde a K = 1 e interpola (es decir, pasa directamente a través de) los datos de entrenamiento. Derecha: La curva azul corresponde a K = 9, y representa un ajuste más suave.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/le.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 18. El mismo conjunto de datos que se muestra en la figura 3.17 se investiga más a fondo. Izquierda: la línea discontinua azul es el ajuste de mínimos cuadrados a los datos. Como f(X) está en hecho lineal (mostrado como la línea negra), la línea de regresión de mínimos cuadrados proporciona una muy buena estimación de f(X). Derecha: La línea horizontal discontinua representa el conjunto de prueba de mínimos cuadrados MSE, mientras que la línea continua verde corresponde al MSE para KNN en función de 1/K (en la escala logarítmica). La regresión lineal logra un MSE de prueba más bajo que la regresión KNN, ya que f(X) es de hecho lineal. Para KNN regresión, los mejores resultados se producen con un valor muy grande de K, correspondiente a un pequeño valor de 1/K.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/l3.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURA 19. Arriba a la izquierda: en un entorno con una relación ligeramente no lineal entre X e Y (línea negra continua), el KNN encaja con K = 1 (azul) y K = 9 (rojo) se muestran. Arriba a la derecha: para los datos ligeramente no lineales, el conjunto de prueba MSE para regresión de mínimos cuadrados (negro horizontal) y KNN con varios valores de Se muestran 1/K (verde). Inferior izquierda e inferior derecha: como en el panel superior, pero con una relación fuertemente no lineal entre X e Y.</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/l4.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">FIGURE 20. Test MSE for linear regression (black dashed lines) and KNN (green curves) as the number of variables p increases. The true function is non– linear in the first variable, as in the lower panel in Figure 3.19, and does not depend on the additional variables. The performance of linear regression deteriorates slowly in the presence of these additional noise variables, whereas KNN's performance degrades much more quickly as p increases.</figcaption><p></p>
</figure>
</div>
</section>
</section>
<section id="lab-cap-3---regresión-linear" class="level1">
<h1>LAB: CAP 3 - Regresión linear</h1>
<p>Librerías a usar:</p>
<p>MASS: colección de conjunto de datos y funciones.</p>
<p>ISLR2: Conjunto de datos asociados al libro de estudio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (MASS)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (ISLR2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ISLR2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:MASS':

    Boston</code></pre>
</div>
</div>
<section id="regresión-linear-simple-1" class="level2">
<h2 class="anchored" data-anchor-id="regresión-linear-simple-1">Regresión linear simple</h2>
<p>La biblioteca ISLR2 contiene el conjunto de datos de Boston, que registra el medv (valor medio de la vivienda) de 506 secciones censales de Boston. Intentaremos predecir medv utilizando 12 predictores como rm (número medio de habitaciones por casa) edad (edad media de las casas) y lstat (porcentaje de hogares con un estatus socioeconómico bajo).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Boston)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     crim zn indus chas   nox    rm  age    dis rad tax ptratio lstat medv
1 0.00632 18  2.31    0 0.538 6.575 65.2 4.0900   1 296    15.3  4.98 24.0
2 0.02731  0  7.07    0 0.469 6.421 78.9 4.9671   2 242    17.8  9.14 21.6
3 0.02729  0  7.07    0 0.469 7.185 61.1 4.9671   2 242    17.8  4.03 34.7
4 0.03237  0  2.18    0 0.458 6.998 45.8 6.0622   3 222    18.7  2.94 33.4
5 0.06905  0  2.18    0 0.458 7.147 54.2 6.0622   3 222    18.7  5.33 36.2
6 0.02985  0  2.18    0 0.458 6.430 58.7 6.0622   3 222    18.7  5.21 28.7</code></pre>
</div>
</div>
<ul>
<li><p><strong>?Boston:</strong> Para obtener información sobre el conjunto de datos.</p></li>
<li><p><strong>lm():</strong> Para ajustar un modelo de regresión lineal simple.</p></li>
<li><p><strong>Predictor:</strong> Istat</p></li>
<li><p><strong>Respuesta:</strong> medv</p></li>
</ul>
<p>La sintaxis básica es lm(y ∼ x, datos), donde y es la respuesta, x es el predictor y datos es el conjunto de datos en el que se mantienen estas dos variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Boston)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>lstat,<span class="at">data =</span> Boston)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>lstat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Si escribimos lm.fit, aparecerá información básica sobre el modelo.</p>
<p>Para obtener información más detallada, utilice summary(lm.fit). Se obtienen los valores p y los errores estándar de los coeficientes, así como el estadístico R2 y el estadístico F del modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm.fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat)

Coefficients:
(Intercept)        lstat  
      34.55        -0.95  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.168  -3.990  -1.318   2.034  24.500 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 34.55384    0.56263   61.41   &lt;2e-16 ***
lstat       -0.95005    0.03873  -24.53   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.216 on 504 degrees of freedom
Multiple R-squared:  0.5441,    Adjusted R-squared:  0.5432 
F-statistic: 601.6 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Podemos utilizar la función names() para averiguar qué otras piezas nombres de información se almacenan en lm.fit.</p>
<p>Es más seguro utilizar las funciones extractoras como coef() para acceder a ellas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "xlevels"       "call"          "terms"         "model"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)       lstat 
 34.5538409  -0.9500494 </code></pre>
</div>
</div>
<p>confint(): Para obtener un intervalo de confianza para las estimaciones de los coeficientes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %     97.5 %
(Intercept) 33.448457 35.6592247
lstat       -1.026148 -0.8739505</code></pre>
</div>
</div>
<p>predict(): Usada para producir intervalos de confianza para la predicción de medv para un valor dado de lstat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lm.fit,<span class="fu">data.frame</span>(<span class="at">lstat=</span>(<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">15</span>))),<span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 29.80359 29.00741 30.59978
2 25.05335 24.47413 25.63256
3 20.30310 19.73159 20.87461</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lm.fit,<span class="fu">data.frame</span>(<span class="at">lstat=</span>(<span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">15</span>))),<span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit       lwr      upr
1 29.80359 17.565675 42.04151
2 25.05335 12.827626 37.27907
3 20.30310  8.077742 32.52846</code></pre>
</div>
</div>
<p>Por ejemplo, el intervalo de confianza del 95 % asociado a un valor lstat de 10 es (24.47, 25.63), y el intervalo de predicción del 95 % es (12.828, 37.28). Como era de esperar, los intervalos de confianza y predicción se centran en el mismo punto (un valor predicho de 10). En el mismo punto (un valor predicho de 25,05 para medv cuando lstat es igual a 10), pero estos últimos son mucho más amplios.</p>
<p>Ahora trazaremos medv y lstat junto con la línea de regresión por mínimos cuadrados utilizando las funciones plot() y abline(). <strong>abline():</strong> se puede usar para agregar líneas verticales, horizontales o de regresión a un gráfico.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lstat,medv)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar indicios de no linealidad en la relación entre lstat y medv.</p>
<p>En la función abline() para dibujar una recta con intersección en a y pendiente b, se escribe <strong>abline(a,b)</strong>. Unos ajustes adicionales para trazar líneas y puntos son:</p>
<ul>
<li><p>lwd: Para la anchura de la línea de regresión.</p></li>
<li><p>pch: Para crear diferentes símbolos de trazado.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lstat,medv)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (lm.fit , <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span> (lm.fit , <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">" red "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (lstat , medv , <span class="at">col =</span> <span class="st">" red "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (lstat , medv , <span class="at">pch =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (lstat , medv , <span class="at">pch =</span> <span class="st">"+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> (<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="at">pch =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-9-5.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>par() y mfrow(): Indicaan a R que divida la pantalla de vizualización en paneles separados para poder visualizar gráficos simultaneamente.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-10-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>residuals (): Para calcular los residuos de un ajuste de regresión lineal.</p>
<p>rstudent(): Devuelve los residuales estudiados y se puede usar para representar gráficamente los residuos frente a los valores ajustados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> ( <span class="fu">predict</span> (lm.fit), <span class="fu">residuals</span> (lm.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> ( <span class="fu">predict</span> (lm.fit), <span class="fu">rstudent</span> (lm.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>hatvalues(): Sirve para calcular los estadísticos utilizando cualquier número de predictores.</p>
<p>which max: identifica el índice del elemento mayor de un vector. En este caso dice que la observación tiene el mayor estadístico de apalancamiento (375).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span> ( <span class="fu">hatvalues</span> (lm.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.max</span>( <span class="fu">hatvalues</span> (lm.fit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>375 
375 </code></pre>
</div>
</div>
</section>
<section id="regresión-lineal-múltiple-1" class="level2">
<h2 class="anchored" data-anchor-id="regresión-lineal-múltiple-1">Regresión lineal múltiple</h2>
<p>Para ajustar un modelo de regresión lineal múltiple por mínimos cuadrados, utilizamos de nuevo la función lm(). La sintaxis lm(y ∼ x1 + x2 + x3) se utiliza para ajustar un modelo con tres predictores, x1, x2 y x3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>lstat<span class="sc">+</span>age,<span class="at">data=</span>Boston)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat + age, data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.981  -3.978  -1.283   1.968  23.158 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 33.22276    0.73085  45.458  &lt; 2e-16 ***
lstat       -1.03207    0.04819 -21.416  &lt; 2e-16 ***
age          0.03454    0.01223   2.826  0.00491 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.173 on 503 degrees of freedom
Multiple R-squared:  0.5513,    Adjusted R-squared:  0.5495 
F-statistic:   309 on 2 and 503 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El conjunto Boston contiene 12 variables por lo que sería más tardado escribir todas las variables, en su lugar se utiliza:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>.,<span class="at">data =</span> Boston)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ ., data = Boston)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.1304  -2.7673  -0.5814   1.9414  26.2526 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  41.617270   4.936039   8.431 3.79e-16 ***
crim         -0.121389   0.033000  -3.678 0.000261 ***
zn            0.046963   0.013879   3.384 0.000772 ***
indus         0.013468   0.062145   0.217 0.828520    
chas          2.839993   0.870007   3.264 0.001173 ** 
nox         -18.758022   3.851355  -4.870 1.50e-06 ***
rm            3.658119   0.420246   8.705  &lt; 2e-16 ***
age           0.003611   0.013329   0.271 0.786595    
dis          -1.490754   0.201623  -7.394 6.17e-13 ***
rad           0.289405   0.066908   4.325 1.84e-05 ***
tax          -0.012682   0.003801  -3.337 0.000912 ***
ptratio      -0.937533   0.132206  -7.091 4.63e-12 ***
lstat        -0.552019   0.050659 -10.897  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.798 on 493 degrees of freedom
Multiple R-squared:  0.7343,    Adjusted R-squared:  0.7278 
F-statistic: 113.5 on 12 and 493 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Para acceder a los componentes específicos de un elemento se escribe: <code>summary(lm.fit)$sigma</code></p>
<p>vif(): utilizada para calcular los factores de inflación de la varianza. Para esto es necesario usar la siguiente librería:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    crim       zn    indus     chas      nox       rm      age      dis 
1.767486 2.298459 3.987181 1.071168 4.369093 1.912532 3.088232 3.954037 
     rad      tax  ptratio    lstat 
7.445301 9.002158 1.797060 2.870777 </code></pre>
</div>
</div>
<p>Para utilizar todas la variables menos una:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>lm.fit1<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>.<span class="sc">-</span>age,<span class="at">data =</span> Boston)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ . - age, data = Boston)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.1851  -2.7330  -0.6116   1.8555  26.3838 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  41.525128   4.919684   8.441 3.52e-16 ***
crim         -0.121426   0.032969  -3.683 0.000256 ***
zn            0.046512   0.013766   3.379 0.000785 ***
indus         0.013451   0.062086   0.217 0.828577    
chas          2.852773   0.867912   3.287 0.001085 ** 
nox         -18.485070   3.713714  -4.978 8.91e-07 ***
rm            3.681070   0.411230   8.951  &lt; 2e-16 ***
dis          -1.506777   0.192570  -7.825 3.12e-14 ***
rad           0.287940   0.066627   4.322 1.87e-05 ***
tax          -0.012653   0.003796  -3.333 0.000923 ***
ptratio      -0.934649   0.131653  -7.099 4.39e-12 ***
lstat        -0.547409   0.047669 -11.483  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.794 on 494 degrees of freedom
Multiple R-squared:  0.7343,    Adjusted R-squared:  0.7284 
F-statistic: 124.1 on 11 and 494 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Como alternativa, puede utilizarse la función update()</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lm.fit1<span class="ot">&lt;-</span><span class="fu">update</span>(lm.fit,<span class="sc">~</span>.<span class="sc">-</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="términos-de-interacción" class="level2">
<h2 class="anchored" data-anchor-id="términos-de-interacción">Términos de interacción</h2>
<p>lstat:black: Indica a R que debe incluir un término de interacción entre lstat y black.</p>
<p>lstat*age: incluye simultaneamente lstat, age, y el término de interacción lstat x age como predictores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(medv<span class="sc">~</span>lstat<span class="sc">*</span>age,<span class="at">data =</span> Boston))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat * age, data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-15.806  -4.045  -1.333   2.085  27.552 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 36.0885359  1.4698355  24.553  &lt; 2e-16 ***
lstat       -1.3921168  0.1674555  -8.313 8.78e-16 ***
age         -0.0007209  0.0198792  -0.036   0.9711    
lstat:age    0.0041560  0.0018518   2.244   0.0252 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.149 on 502 degrees of freedom
Multiple R-squared:  0.5557,    Adjusted R-squared:  0.5531 
F-statistic: 209.3 on 3 and 502 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="transformaciones-no-lineales-de-los-predictores" class="level2">
<h2 class="anchored" data-anchor-id="transformaciones-no-lineales-de-los-predictores">Transformaciones no lineales de los predictores</h2>
<p>lm puede ser ajustada a transformaciones no lineales de los predictores. La función I() es necesaria ya que el ^ tiene un significado especial I() en un objeto de fórmula; permite el uso estándar en R, que es elevar X a la potencia 2. Ahora realizamos una regresión de medv sobre lstat y lstat2.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lm.fit2<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>lstat<span class="sc">+</span><span class="fu">I</span>(lstat<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ lstat + I(lstat^2))

Residuals:
     Min       1Q   Median       3Q      Max 
-15.2834  -3.8313  -0.5295   2.3095  25.4148 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 42.862007   0.872084   49.15   &lt;2e-16 ***
lstat       -2.332821   0.123803  -18.84   &lt;2e-16 ***
I(lstat^2)   0.043547   0.003745   11.63   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.524 on 503 degrees of freedom
Multiple R-squared:  0.6407,    Adjusted R-squared:  0.6393 
F-statistic: 448.5 on 2 and 503 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El valor p casi nulo asociado al término cuadrático sugiere modelo mejorado.</p>
<p>anova(): Sirve para cuantificar mejor hasta qué punto el ajuste cuadrático es superior al lineal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span>lstat)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm.fit,lm.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: medv ~ lstat
Model 2: medv ~ lstat + I(lstat^2)
  Res.Df   RSS Df Sum of Sq     F    Pr(&gt;F)    
1    504 19472                                 
2    503 15347  1    4125.1 135.2 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Modelo 1: Representa el submodelo lineal que tiene un solo predictor (lstat).</p>
<p>Modelo 2: Modelo cuadrático más amplico con dos predictores (lstat y lstat^2).</p>
<p>La función anova realiza una pruea de hipótesis que compara los dos modelos.</p>
<p>Una hipótesis nula quiere decir que los dos modelos se ajustan correctamente a los datos.</p>
<p>Una hipótesis alternativa significa que el modelo es superior.</p>
<p>En este caso, el estadístico F es 135 y el valor p asociado es prácticamente cero. Esto demuestra claramente que el modelo que contiene los predictores lstat y lstat2 es muy superior al modelo que sólo contiene el predictor lstat. Esto quiere decir que no existe linelidad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm.fit2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-21-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-21-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Resumen-2---3_files/figure-html/unnamed-chunk-21-4.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cuando se incluye lstat2 en el modelo se puede observar que hay pocos patrones dicernibles en los residuos.</p>
<p>Par crear un ajuste mayor se puede utilizar la función <strong>poly()</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>lm.fit5<span class="ot">&lt;-</span><span class="fu">lm</span>(medv<span class="sc">~</span><span class="fu">poly</span>(lstat,<span class="dv">5</span>))</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ poly(lstat, 5))

Residuals:
     Min       1Q   Median       3Q      Max 
-13.5433  -3.1039  -0.7052   2.0844  27.1153 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       22.5328     0.2318  97.197  &lt; 2e-16 ***
poly(lstat, 5)1 -152.4595     5.2148 -29.236  &lt; 2e-16 ***
poly(lstat, 5)2   64.2272     5.2148  12.316  &lt; 2e-16 ***
poly(lstat, 5)3  -27.0511     5.2148  -5.187 3.10e-07 ***
poly(lstat, 5)4   25.4517     5.2148   4.881 1.42e-06 ***
poly(lstat, 5)5  -19.2524     5.2148  -3.692 0.000247 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.215 on 500 degrees of freedom
Multiple R-squared:  0.6817,    Adjusted R-squared:  0.6785 
F-statistic: 214.2 on 5 and 500 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Incluir términos de hasta quinto orden mejora el ajuste del modelo, pero si son mayores a este orden el modelo no tendrá valores p significativos en el ajuste de regresión.</p>
<p>Para obtener los polinomios brutos de la función poly(), debe utilizarse el argumento raw = TRUE.</p>
<p><strong>Tranformación logarítmica:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(medv<span class="sc">~</span><span class="fu">log</span>(rm),<span class="at">data =</span> Boston))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = medv ~ log(rm), data = Boston)

Residuals:
    Min      1Q  Median      3Q     Max 
-19.487  -2.875  -0.104   2.837  39.816 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -76.488      5.028  -15.21   &lt;2e-16 ***
log(rm)       54.055      2.739   19.73   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.915 on 504 degrees of freedom
Multiple R-squared:  0.4358,    Adjusted R-squared:  0.4347 
F-statistic: 389.3 on 1 and 504 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="predictores-cualitativos-1" class="level2">
<h2 class="anchored" data-anchor-id="predictores-cualitativos-1">Predictores cualitativos</h2>
<p>Para esta parte se usará: Carseats data para intentar predecir las ventas de asientos de autos en 4000 localidades basado en una serie de predictores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Carseats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sales CompPrice Income Advertising Population Price ShelveLoc Age Education
1  9.50       138     73          11        276   120       Bad  42        17
2 11.22       111     48          16        260    83      Good  65        10
3 10.06       113     35          10        269    80    Medium  59        12
4  7.40       117    100           4        466    97    Medium  55        14
5  4.15       141     64           3        340   128       Bad  38        13
6 10.81       124    113          13        501    72       Bad  78        16
  Urban  US
1   Yes Yes
2   Yes Yes
3   Yes Yes
4   Yes Yes
5   Yes  No
6    No Yes</code></pre>
</div>
</div>
<p>Predictores cualitativos incluidos: Shelveloc (calidad de la ubicación de la estantería). Tiene 3 valores posibles: Malo, medio y bueno. A continuación ajustamos un modelo de regresión múltiple que incluye algunos términos de interacción.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>lm.fit<span class="ot">&lt;-</span><span class="fu">lm</span>(Sales<span class="sc">~</span>.<span class="sc">+</span>Income<span class="sc">:</span>Advertising<span class="sc">+</span>Price<span class="sc">:</span>Age,<span class="at">data =</span> Carseats)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Sales ~ . + Income:Advertising + Price:Age, data = Carseats)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.9208 -0.7503  0.0177  0.6754  3.3413 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         6.5755654  1.0087470   6.519 2.22e-10 ***
CompPrice           0.0929371  0.0041183  22.567  &lt; 2e-16 ***
Income              0.0108940  0.0026044   4.183 3.57e-05 ***
Advertising         0.0702462  0.0226091   3.107 0.002030 ** 
Population          0.0001592  0.0003679   0.433 0.665330    
Price              -0.1008064  0.0074399 -13.549  &lt; 2e-16 ***
ShelveLocGood       4.8486762  0.1528378  31.724  &lt; 2e-16 ***
ShelveLocMedium     1.9532620  0.1257682  15.531  &lt; 2e-16 ***
Age                -0.0579466  0.0159506  -3.633 0.000318 ***
Education          -0.0208525  0.0196131  -1.063 0.288361    
UrbanYes            0.1401597  0.1124019   1.247 0.213171    
USYes              -0.1575571  0.1489234  -1.058 0.290729    
Income:Advertising  0.0007510  0.0002784   2.698 0.007290 ** 
Price:Age           0.0001068  0.0001333   0.801 0.423812    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.011 on 386 degrees of freedom
Multiple R-squared:  0.8761,    Adjusted R-squared:  0.8719 
F-statistic:   210 on 13 and 386 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>contrasts() devuelve la codificación que R utiliza para las variables ficticias.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(Carseats)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(ShelveLoc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Good Medium
Bad       0      0
Good      1      0
Medium    0      1</code></pre>
</div>
</div>
<p>ShelveLocGood que toma un valor de 1 si la ubicación de la estantería es buena, y 0 en caso contrario.</p>
<p>El hecho de que el coeficiente de ShelveLocGood en el resultado de la regresión sea positivo indica que una buena estanterías se asocia a ventas elevadas (en comparación con las malas).</p>
<p>ShelveLocMedium tiene un coeficiente positivo menor, lo que indica tiene ubicación media de las estanterías se asocia a mayores ventas que a una mala ubicación, pero con menores ventas que una buena ubicación.</p>
</section>
<section id="funciones-de-escritura" class="level2">
<h2 class="anchored" data-anchor-id="funciones-de-escritura">Funciones de escritura</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>LoadLibraries <span class="ot">&lt;-</span> <span class="cf">function</span> () {</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (ISLR2)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span> (MASS)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span> (<span class="st">"The libraries have been loaded ."</span>)</span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ahora si se escribe LoadLibraries, R dirá qué contiene la función.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>LoadLibraries</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>function () {
library (ISLR2)
library (MASS)
print ("The libraries have been loaded .")
}</code></pre>
</div>
</div>
<p>Si llamamos a la función, las librerías se cargan y la sentencia print se imprime.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">LoadLibraries</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "The libraries have been loaded ."</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>